---
# add-apt-repository ppa:ondrej/php
- name: add-apt-repository
  ansible.builtin.apt_repository:
    repo: ppa:ondrej/php

# apt install php7.3 php7.3-bcmath php7.3-curl php7.3-json php7.3-mbstring php7.3-mysql php7.3-xml php7.3-zip php7.3-fpm
- name: php install
  apt:
    name:
      - php7.3
      - php7.3-bcmath
      - php7.3-curl
      - php7.3-json
      - php7.3-mbstring
      - php7.3-mysql
      - php7.3-xml
      - php7.3-zip
      - php7.3-fpm
